export enum ProjectState {
  CANCELED = 1,
  BEFORE_FUNDRAISER,
  FAILED_FUNDRAISER,
  ONGOING_FUNDRAISER,
  FUNDRAISER_ENDED_NO_MILESTONES_ONGOING,
  MILESTONES_ONGOING_BEFORE_LAST,
  LAST_MILESTONE_ONGOING,
  TERMINATED_BY_VOTING,
  TERMINATED_DUE_TO_INACTIVITY,
  SUCCESSFULLY_ENDED,
  UNKNOWN,
}
