name: Install and Build for PR

on:
  pull_request:
    branches:    
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: yarn install, build
      run: |
        yarn install --frozen-lockfile
        yarn build